### PR TITLE
Suppress deprecated function notices on PHP 8.1

### PR DESCRIPTION
**Pull request by noahott**
Suppress deprecated function notices when implementing ArrayAccess::offsetExists (and offsetGet, offsetSet, offsetUnset) methods by adding #[\ReturnTypeWillChange]

### CODE REVIEW

**Comment by enricobono** [comment]
Thanks, @noahott!
+1 on this PR!

**Comment by justinyost** [comment]
@noahott Any chance you can rebase this against the latest changes, otherwise it would be great to merge this in.

**Comment by noahott** [comment]
@justinyost my fork is now up to date with yours

**Review by justinyost — APPROVED** [review]
LGTM 👍 Thanks.

**Comment by offsky** [comment]
Thanks to @noahott for taking the initiative to bring the PAAPI up to 8.1 compatibility.  I just wanted to note that there are many more places within this library which give warnings for offsetExists, offsetGet, offsetSet, offsetUnset than the ones fixed in this pull request. You would encounter them if you accessed different attributes of the returned data. They can all be fixed by #[\ReturnTypeWillChange] so if you want to fully fix this problem its some more find and replace.  

I am sorry that I dont have time to put in pull request to make a full fix right now, but hopefully this comment helps someone in the future.

**Pull request merged**
